### ISSUE TITLE
Enhance: Remove Limitations

### ISSUE THREAD

**Issue by Likqez** [satoqz/rapla#20]
**Issue: Simplify Proxy Tool Constraints**

**Description:**
The tool is meant to function solely as a proxy, which it currently doesn't adhere to. I suggest removing the requirement for specific paths like `rapla/calendar` and keeping it generalized.

**Proposal:**
Let's simplify by serving every request at `/rapla/**`, with failure occurring if the URL doesn't provide a parseable Rapla result. This way, users can use any URL they have without limitations.

**Comment by Likqez** [comment]
This also requires the caching system to be altered, so it's not solely relying on the rapla key.

**Comment by satoqz** [comment]
What cache key do you suggest we use?

**Comment by Likqez** [comment]
I would suggest `(cal_type, key)` whilst cal_type being a capture of `<host>/rapla/:cal_type`

**Comment by satoqz** [comment]
I put something together in #21, have a look
